from pathlib import Path

DATABASE_PATH = Path('./data/llama.db')

# MODEL_URL = "https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf"
# MODEL_URL = "https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/"
# MODEL_URL = "https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct"
PDF_FILE_PATH = "./data/llama2.pdf"
EMBED_MODEL_NAME = "BAAI/bge-small-en"

LLM_TEMPERATURE = 0.1
LLM_MAX_NEW_TOKENS = 384
LLM_CONTEXT_WINDOW = 3900
LLM_MODEL_KWARGS = {"n_gpu_layers": 1}
LLM_VERBOSE = False

CHUNK_SIZE = 128
CHUNK_OVERLAP = 50
NODE_TOP_K = 20
DOCUMENT_TOP_K = 3
QUERY_MODE = "default"

# Languge model
MODELS_PATH = Path('./models/')
FASTTEXT_MODEL = 'lid.176.ftz'
FASTTEXT_LANGUAGES_MAP = {
    "af": "Afrikaans",
    "als": "Alemannic German",
    "am": "Amharic",
    "an": "Aragonese",
    "ar": "Arabic",
    "arz": "Egyptian Arabic",
    "as": "Assamese",
    "ast": "Asturian",
    "av": "Avaric",
    "az": "Azerbaijani",
    "azb": "South Azerbaijani",
    "ba": "Bashkir",
    "bar": "Bavarian",
    "bcl": "Central Bikol",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bh": "Bihari languages",
    "bn": "Bengali",
    "bo": "Tibetan",
    "bpy": "Bishnupriya Manipuri",
    "br": "Breton",
    "bs": "Bosnian",
    "bxr": "Buriat",
    "ca": "Catalan",
    "cbk": "Chavacano (Zamboanga)",
    "ce": "Chechen",
    "ceb": "Cebuano",
    "ckb": "Central Kurdish (Sorani)",
    "co": "Corsican",
    "cs": "Czech",
    "cv": "Chuvash",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "diq": "Dimli (Zaza)",
    "dsb": "Lower Sorbian",
    "dty": "Doteli",
    "dv": "Dhivehi",
    "el": "Greek",
    "eml": "Emilian-Romagnol",
    "en": "English",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fr": "French",
    "frr": "Northern Frisian",
    "fy": "Western Frisian",
    "ga": "Irish",
    "gd": "Scottish Gaelic",
    "gl": "Galician",
    "gn": "Guarani",
    "gom": "Goan Konkani",
    "gu": "Gujarati",
    "gv": "Manx",
    "he": "Hebrew",
    "hi": "Hindi",
    "hif": "Fiji Hindi",
    "hr": "Croatian",
    "hsb": "Upper Sorbian",
    "ht": "Haitian Creole",
    "hu": "Hungarian",
    "hy": "Armenian",
    "ia": "Interlingua",
    "id": "Indonesian",
    "ie": "Interlingue",
    "ilo": "Ilocano",
    "io": "Ido",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "jbo": "Lojban",
    "jv": "Javanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Khmer",
    "kn": "Kannada",
    "ko": "Korean",
    "krc": "Karachay-Balkar",
    "ku": "Kurdish",
    "kv": "Komi",
    "kw": "Cornish",
    "ky": "Kyrgyz",
    "la": "Latin",
    "lb": "Luxembourgish",
    "lez": "Lezghian",
    "li": "Limburgish",
    "lmo": "Lombard",
    "lo": "Lao",
    "lrc": "Northern Luri",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mai": "Maithili",
    "mg": "Malagasy",
    "mhr": "Eastern Mari",
    "min": "Minangkabau",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "mr": "Marathi",
    "mrj": "Western Mari",
    "ms": "Malay",
    "mt": "Maltese",
    "mwl": "Mirandese",
    "my": "Burmese",
    "myv": "Erzya",
    "mzn": "Mazanderani",
    "nah": "Nahuatl",
    "nap": "Neapolitan",
    "nds": "Low German",
    "ne": "Nepali",
    "new": "Newar (Newari)",
    "nl": "Dutch",
    "nn": "Norwegian Nynorsk",
    "no": "Norwegian",
    "oc": "Occitan",
    "or": "Oriya (Odia)",
    "os": "Ossetian",
    "pa": "Punjabi",
    "pam": "Pampanga",
    "pfl": "Palatine German",
    "pl": "Polish",
    "pms": "Piedmontese",
    "pnb": "Western Punjabi",
    "ps": "Pashto",
    "pt": "Portuguese",
    "qu": "Quechua",
    "rm": "Romansh",
    "ro": "Romanian",
    "ru": "Russian",
    "rue": "Rusyn",
    "sa": "Sanskrit",
    "sah": "Yakut",
    "sc": "Sardinian",
    "scn": "Sicilian",
    "sco": "Scots",
    "sd": "Sindhi",
    "sh": "Serbo-Croatian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "sq": "Albanian",
    "sr": "Serbian",
    "su": "Sundanese",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "tg": "Tajik",
    "th": "Thai",
    "tk": "Turkmen",
    "tl": "Tagalog",
    "tr": "Turkish",
    "tt": "Tatar",
    "tyv": "Tuvinian",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vec": "Venetian",
    "vep": "Veps",
    "vi": "Vietnamese",
    "vls": "West Flemish",
    "vo": "Volapük",
    "wa": "Walloon",
    "war": "Waray",
    "wuu": "Wu Chinese",
    "xal": "Kalmyk",
    "xmf": "Mingrelian",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yue": "Cantonese",
    "zh": "Chinese",
}
